name: Profile Stack

on:
  schedule:
    # Runs every hour
    - cron: "0 0 * * *"
  push:
    branches:
      - master
jobs:
  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Matt-Gleich/profile_stack@master
